-- Create DEPARTMENT table
CREATE TABLE DEPARTMENT (
    DEPT_NAME VARCHAR(100) NOT NULL,
    DEPT_LOCATION VARCHAR(100),
    DEPT_FACILITY VARCHAR(100),
    CONSTRAINT PK_DEPT_NAME PRIMARY KEY (DEPT_NAME)
);
-- Create ALL_DOCTORS table
CREATE TABLE ALL_DOCTORS(
DOC_ID VARCHAR(100) CONSTRAINT CHECK_PREFIX CHECK(DOC_ID LIKE 'DC%' OR DOC_ID LIKE 'DR') NOT NULL ,
DEPT_NAME VARCHAR(100) CONSTRAINT DEPT_NAME_FK REFERENCES DEPARTMENT(DEPT_NAME),
DOC_NAME VARCHAR(100),
	CONSTRAINT PK_COMPOSITE_DOC_ID PRIMARY KEY (DOC_ID,DOC_NAME)
)

-- Create DOC_REG table
CREATE TABLE DOC_REG(
DOC_ID VARCHAR(100) CHECK(DOC_ID LIKE'DR%') NOT NULL ,
DOC_NAME VARCHAR(100),
	QUAL VARCHAR(100),
	ADDRESS VARCHAR(100),
	PHONE VARCHAR(100),
	SALARY NUMERIC(10,2),
	DATE_JOIN DATE,
	CONSTRAINT PK_COMPOSITE_DOC_ID_2 PRIMARY KEY(DOC_ID,DOC_NAME) ,
	CONSTRAINT FK_COMPOSITE_DOC_ID_NAME FOREIGN KEY(DOC_ID,DOC_NAME) REFERENCES ALL_DOCTORS(DOC_ID,DOC_NAME)
)

-- Create DOC_ON_CALL table
CREATE TABLE DOC_ON_CALL
(
DOC_ID VARCHAR(100) CHECK(DOC_ID LIKE'DC%') NOT NULL ,
DOC_NAME VARCHAR(100),
QUAL VARCHAR(100),
ADDRESS VARCHAR(100),
PHONE VARCHAR(100),
FEE_PER_CALL NUMERIC(10,2),
PAYMENT_DUE NUMERIC(10,2) ,
PRIMARY KEY(DOC_ID,DOC_NAME),
FOREIGN KEY (DOC_ID,DOC_NAME)REFERENCES ALL_DOCTORS(DOC_ID,DOC_NAME)
)

-- Create PAT_ENTRY table
CREATE TABLE PAT_ENTRY (
    PATIENT_NO VARCHAR(100) NOT NULL,
    DOC_ID VARCHAR(100) NOT NULL,
    PATIENT_NAME VARCHAR(100),
    PATIENT_AGE VARCHAR(5),
    SEX CHAR(1) CHECK (SEX IN ('M', 'F')),
    ADDRESS VARCHAR(150),
    CITY VARCHAR(50),
    PHONE VARCHAR(100),
    PATIENT_ENTRY_DATE DATE,
    DOC_NAME VARCHAR(100),
    DEPT_NAME VARCHAR(100),
    DIAGNOSIS TEXT,
    CONSTRAINT PK_PAT_ENTRY PRIMARY KEY (PATIENT_NO),
    CONSTRAINT FK_PAT_ENTRY_ALL_DOCTORS FOREIGN KEY (DOC_ID, DOC_NAME) REFERENCES ALL_DOCTORS (DOC_ID, DOC_NAME),
    CONSTRAINT FK_PAT_ENTRY_DEPARTMENT FOREIGN KEY (DEPT_NAME) REFERENCES DEPARTMENT (DEPT_NAME)
);

-- Create PAT_CHKUP table
CREATE TABLE PAT_CHKUP (
    CHKUP_ID VARCHAR(100) NOT NULL,
    PATIENT_NO VARCHAR(100),
    DOC_ID VARCHAR(100) NOT NULL,
    DOC_NAME VARCHAR(100),
    DATE_CHECK_UP DATE,
    DIAGNOSIS TEXT,
    TREATMENT TEXT,
    STATUS VARCHAR(100),
    CONSTRAINT PK_PAT_CHKUP PRIMARY KEY (CHKUP_ID),
    CONSTRAINT FK_PAT_CHKUP_PAT_ENTRY FOREIGN KEY (PATIENT_NO) REFERENCES PAT_ENTRY (PATIENT_NO),
    CONSTRAINT FK_PAT_CHKUP_ALL_DOCTORS FOREIGN KEY (DOC_ID, DOC_NAME) REFERENCES ALL_DOCTORS (DOC_ID, DOC_NAME)
);

-- Create PAT_ADMIT table
CREATE TABLE PAT_ADMIT
(
	ADMIT_ID VARCHAR(100) ,
    PATIENT_NO VARCHAR(255) REFERENCES PAT_ENTRY(PATIENT_NO),
    Advance_Payment DECIMAL(10, 2),
    Mode_of_Payment VARCHAR(255),
    Room_Number VARCHAR(255), --,
    Date_of_Admission DATE,
    Initial_Condition TEXT,
    Diagnosis TEXT,
    Treatment TEXT,
    DOC_ID VARCHAR(100)CHECK(DOC_ID LIKE 'DC%' OR DOC_ID LIKE 'DR') NOT NULL,
DOC_NAME VARCHAR(100),
    Attendant_Name VARCHAR(255),
	FOREIGN KEY(DOC_ID,DOC_NAME) REFERENCES ALL_DOCTORS(DOC_ID,DOC_NAME),
	PRIMARY KEY(ADMIT_ID,PATIENT_NO)
)

ALTER TABLE PAT_ADMIT
ADD CONSTRAINT FK_ROOM FOREIGN KEY (Room_Number) REFERENCES ROOM_DETAILS(Room_Number)

-- Create PAT_DIS table
CREATE TABLE PAT_DIS (
    Discharge_ID VARCHAR(100) PRIMARY KEY,
    PATIENT_NO VARCHAR(255),
    Treatment_Given TEXT,
    Treatment_Advice TEXT,
    Payment_Made DECIMAL(10, 2),
    Mode_of_Payment VARCHAR(255),
    Date_of_Discharge DATE,
    CONSTRAINT FK_PAT_DIS_PAT_ENTRY FOREIGN KEY (PATIENT_NO) REFERENCES PAT_ENTRY (PATIENT_NO)
);
-- Create PAT_REG table
CREATE TABLE PAT_REG (
    Reg_ID VARCHAR(100) PRIMARY KEY,
    PATIENT_NO VARCHAR(255),
    Date_of_Visit DATE,
    Diagnosis TEXT,
    Treatment TEXT,
    Medicine_Recommended TEXT,
    Status_of_Treatment VARCHAR(255),
    CONSTRAINT FK_PAT_REG_PAT_ENTRY FOREIGN KEY (PATIENT_NO) REFERENCES PAT_ENTRY (PATIENT_NO)
);

CREATE TABLE PAT_OPR (
    Operation_ID VARCHAR(100) PRIMARY KEY,
    PATIENT_NO VARCHAR(255),
    Date_of_Admission DATE,
    Date_of_Operation DATE,
    DOC_ID VARCHAR(100) NOT NULL,
    DOC_NAME VARCHAR(100),
    Operation_Theater_Number VARCHAR(255),
    Type_of_Operation TEXT,
    Patient_Condition_Before TEXT,
    Patient_Condition_After TEXT,
    Treatment_Advice TEXT,
    CONSTRAINT FK_PAT_OPR_PAT_ENTRY FOREIGN KEY (PATIENT_NO) REFERENCES PAT_ENTRY (PATIENT_NO),
    CONSTRAINT FK_PAT_OPR_ALL_DOCTORS FOREIGN KEY (DOC_ID, DOC_NAME) REFERENCES ALL_DOCTORS (DOC_ID, DOC_NAME)
);
ALTER TABLE PAT_OPR
ADD CONSTRAINT FK_ROOM_1 FOREIGN KEY (Operation_Theater_Number) REFERENCES ROOM_DETAILS(Room_Number)
-- Create ROOM_DETAILS table
CREATE TABLE ROOM_DETAILS (
    Room_Number VARCHAR(255) PRIMARY KEY,
	ADMIT_ID VARCHAR(100) ,
    Room_Type CHAR(1) CHECK (Room_Type IN ('G', 'P')),
    Status CHAR(1) CHECK (Status IN ('Y', 'N')),
    PATIENT_NO VARCHAR(255) ,
    Charges_Per_Day DECIMAL(10, 2),
	FOREIGN KEY (ADMIT_ID,PATIENT_NO) REFERENCES PAT_ADMIT(ADMIT_ID,PATIENT_NO)
);
